version: "3.9"

services:
  web:
    image: ghcr.io/bondbenbond/werewolf-web:${WEB_TAG}
    networks:
      - caddy-net
    expose:
      - "80"

  server:
    image: ghcr.io/bondbenbond/werewolf-server:${SERVER_TAG}
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - caddy-net
    expose:
      - "4000"

networks:
  caddy-net:
    external: true
