version: "3.9"

services:
  web:
    container_name: werewolf-web-test
    volumes:
      - ./env.web.test.json:/usr/share/nginx/html/assets/env.json:ro
    networks:
      caddy-net:
        aliases:
          - werewolf-web-test

  server:
    container_name: werewolf-server-test
    networks:
      caddy-net:
        aliases:
          - werewolf-server-test
