version: "3.9"

services:
  web:
    container_name: werewolf-web
    volumes:
      - ./env.web.prod.json:/usr/share/nginx/html/assets/env.json:ro
    networks:
      caddy-net:
        aliases:
          - werewolf-web

  server:
    container_name: werewolf-server
    networks:
      caddy-net:
        aliases:
          - werewolf-server
