services:
  web:
    image: ghcr.io/bondbenbond/werewolf-web:${WEB_TAG}
    container_name: werewolf-web
    expose:
      - "80"
    volumes:
      - ./env.web.prod.json:/usr/share/nginx/html/assets/env.json:ro
    networks:
      caddy-net:
        aliases:
          - werewolf-web

  server:
    image: ghcr.io/bondbenbond/werewolf-server:${SERVER_TAG}
    container_name: werewolf-server
    environment:
      NODE_ENV: ${NODE_ENV}
    expose:
      - "4000"
    networks:
      caddy-net:
        aliases:
          - werewolf-server

networks:
  caddy-net:
    external: true
